### ISSUE TITLE
Variable GLOBAL_PROJECT_ID utility

### ISSUE THREAD

**Issue by Pseudodevincent** [flyflyinit/certbot-dns-challenge-flexibleengine#2]
Hello @flyflyinit, I don't understand what is this VARIABLE ?
I put the same projectid than in PROJECT_ID and it works.

**Comment by flyflyinit** [comment]
Hello @Pseudodevincent , DNS records are managed and provisioned globally on a global project, so they require global project Token authentication, for example (region eu-west-0).

**Comment by flyflyinit** [comment]
Issue fixed, Authenticatoin with single PROJECT_ID.
